### ISSUE TITLE
opennms dependancies issues- ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by spiritus72** [opennms-forge/opennms-install#15]
Hi, I am trying to install opennms on a fresh new install of Ubuntu 18.04 LTS. I am running into the following issues that i am unable to resolve.

Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
opennms : Depends: opennms-server (= 22.0.3-1) but it is not going to be installed
Depends: opennms-webapp-jetty (= 22.0.3-1) but it is not going to be installed
Recommends: opennms-source (= 22.0.3-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
FAILED

**Comment by indigo423** [comment]
The first thing I notice, you try to install 22.0.3-1 which is not the current stable release. The current stable is 22.0.4-1. I've tried to reproduce the issue in a vagrant box using `vagrant init ubuntu/bionic64` and ran the `curl -L https://github.com/opennms-forge/opennms-install/archive/1.3.tar.gz | tar xz. The install finished without problems.

**Comment by spiritus72** [comment]
Thanks for answering @indigo423 . I actually ran the stable release and it gave me the same errors with the current version number.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 opennms : Depends: opennms-server (= 22.0.4-1) but it is not going to be installed
           Depends: opennms-webapp-jetty (= 22.0.4-1) but it is not going to be installed
           Recommends: opennms-source (= 22.0.4-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
FAILED

I will try to reproduce it in a vagrant box and let you know how it goes.

**Comment by indigo423** [comment]
Can you please have a look which IP address for debian.mirror.org you use? We have location specific routing and I can pin my system to the same mirror to use the same source. I'm located in Germany and use probably a different one than you.

**Comment by spiritus72** [comment]
Actually I was able to fix it without using a vagrant box. The issue was that not all my ubuntu repositories were enabled. Thank you so much for your help.

**Comment by indigo423** [comment]
Glad you figured it out. Thank you for sharing your findings to help others.
