### ISSUE TITLE
opennms dashboard does not load on browser.

### ISSUE THREAD

**Issue by ghostbill** [opennms-forge/opennms-install#16]
Hi @indigo423 

I have installed opennms and when trying to load it on the browser I get a 404 error page. What can be the issue? The apache browser index page loads.

Thanks!

**Comment by indigo423** [comment]
@spiritus72 It seems like this is a very generic install question. Can you please join the community in the "opennms-discuss" channel on https://chat.opennms.com to get help with your install problem? Thank you very much.

**Comment by indigo423** [comment]
Meanwhile you can also ask this type of questions in https://opennms.discourse.group. Can you please move this topic there and close this issue here? Thank you very much.
