### ISSUE TITLE
Problem installing openNMS on Centos 7.6

### ISSUE THREAD

**Issue by ngysim** [opennms-forge/opennms-install#17]
PostgreSQL initialize                 ... FAILED
[root@localhost opennms-install-1.3]# systemctl start opennms
Job for opennms.service failed because the control process exited with error code. See "systemctl status opennms.service" and "journalctl -xe" for details.

[root@localhost opennms-install-1.3]# systemctl status opennms.service
● opennms.service - OpenNMS server
   Loaded: loaded (/usr/lib/systemd/system/opennms.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2018-12-07 15:33:00 +07; 40s ago
  Process: 24240 ExecStart=/opt/opennms/bin/opennms -Q start (code=exited, status=1/FAILURE)

Dec 07 15:33:00 localhost.localdomain opennms[24240]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
Dec 07 15:33:00 localhost.localdomain opennms[24240]: at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
Dec 07 15:33:00 localhost.localdomain opennms[24240]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Dec 07 15:33:00 localhost.localdomain opennms[24240]: ... 8 more
Dec 07 15:33:00 localhost.localdomain opennms[24240]: Unknown value return from doStatus: 1
Dec 07 15:33:00 localhost.localdomain opennms[24240]: [FAILED]
Dec 07 15:33:00 localhost.localdomain systemd[1]: opennms.service: control process exited, code=exited status=1
Dec 07 15:33:00 localhost.localdomain systemd[1]: Failed to start OpenNMS server.
Dec 07 15:33:00 localhost.localdomain systemd[1]: Unit opennms.service entered failed state.
Dec 07 15:33:00 localhost.localdomain systemd[1]: opennms.service failed.

[root@localhost opennms-install-1.3]# journalctl -xe
-- 
-- Unit opennms.service has begun starting up.
Dec 07 15:33:00 localhost.localdomain opennms[24240]: Starting OpenNMS: Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/attac
Dec 07 15:33:00 localhost.localdomain opennms[24240]: at java.lang.Class.getDeclaredMethods0(Native Method)
Dec 07 15:33:00 localhost.localdomain opennms[24240]: at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
Dec 07 15:33:00 localhost.localdomain opennms[24240]: at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
Dec 07 15:33:00 localhost.localdomain opennms[24240]: at java.lang.Class.getMethod0(Class.java:3018)
Dec 07 15:33:00 localhost.localdomain opennms[24240]: at java.lang.Class.getMethod(Class.java:1784)
Dec 07 15:33:00 localhost.localdomain opennms[24240]: at org.opennms.bootstrap.Bootstrap.executeClass(Bootstrap.java:519)
Dec 07 15:33:00 localhost.localdomain opennms[24240]: at org.opennms.bootstrap.Bootstrap.executeClass(Bootstrap.java:481)
Dec 07 15:33:00 localhost.localdomain opennms[24240]: at org.opennms.bootstrap.Bootstrap.main(Bootstrap.java:477)
Dec 07 15:33:00 localhost.localdomain opennms[24240]: Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.AttachNotSupportedException
Dec 07 15:33:00 localhost.localdomain opennms[24240]: at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
Dec 07 15:33:00 localhost.localdomain opennms[24240]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
Dec 07 15:33:00 localhost.localdomain opennms[24240]: at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
Dec 07 15:33:00 localhost.localdomain opennms[24240]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Dec 07 15:33:00 localhost.localdomain opennms[24240]: ... 8 more
Dec 07 15:33:00 localhost.localdomain opennms[24240]: Unknown value return from doStatus: 1
Dec 07 15:33:00 localhost.localdomain opennms[24240]: [FAILED]
Dec 07 15:33:00 localhost.localdomain systemd[1]: opennms.service: control process exited, code=exited status=1
Dec 07 15:33:00 localhost.localdomain systemd[1]: Failed to start OpenNMS server.
-- Subject: Unit opennms.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit opennms.service has failed.
-- 
-- The result is failed.
Dec 07 15:33:00 localhost.localdomain systemd[1]: Unit opennms.service entered failed state.
Dec 07 15:33:00 localhost.localdomain systemd[1]: opennms.service failed.
Dec 07 15:33:00 localhost.localdomain polkitd[8184]: Unregistered Authentication Agent for unix-process:24234:183642 (system bus name :1.255, object p
Dec 07 15:33:22 localhost.localdomain nautilus-deskto[19991]: g_simple_action_set_enabled: assertion 'G_IS_SIMPLE_ACTION (simple)' failed
Dec 07 15:33:38 localhost.localdomain nautilus-deskto[19991]: g_simple_action_set_enabled: assertion 'G_IS_SIMPLE_ACTION (simple)' failed
Dec 07 15:33:49 localhost.localdomain nautilus-deskto[19991]: g_simple_action_set_enabled: assertion 'G_IS_SIMPLE_ACTION (simple)' failed

**Comment by indigo423** [comment]
Can you please share the content of your bootstrap.log file?

**Comment by indigo423** [comment]
@ngysim does this issue still exist or can we close it?

**Comment by evelbodevil** [comment]
What did you do to resolve this issue?

**Comment by indigo423** [comment]
> What did you do to resolve this issue?

See answer above, 

> Can you please share the content of your bootstrap.log file?

**Comment by indigo423** [comment]
If this issue still exist, please re-open.
