### ISSUE TITLE
suggestion: Ubuntu installation requires 'universe' repository in /etc/apt/sources.list

### ISSUE THREAD

**Issue by SandMouse** [opennms-forge/opennms-install#18]
Ubuntu 18.04 LTS installation requires 'universe' repository in /etc/apt/sources.list, this is not explicitly stated in the Quick Installation page: "https://www.opennms.org/en/install-debian".

[edit] added ubuntu version [/edit]

**Comment by indigo423** [comment]
Hello thank you very much for the hint. You're definitely right, we ran in this [issue](https://issues.opennms.org/browse/NMS-10503) already and the installer doesn't tell you anything about it. I've added a hint on the web page. Do you think this solves this issue? If not don't hesitate and reopen the issue.

Thank you very much for your feedback and taking care.
