### ISSUE TITLE
Failed to install  on RHEL 7.5

### ISSUE THREAD

**Issue by keylowgee** [opennms-forge/opennms-install#19]
From a fresh VM I tried to install using the quick installer (https://opennms.org/en/install-centos).

Here is my output from the install log (only was able to get a partial capture).

 Verifying  : jicmp6-2.0.2-1.el7.centos.x86_64                             1/8
  Verifying  : jicmp-2.0.3-1.el7.centos.x86_64                              2/8
  Verifying  : opennms-23.0.4-1.noarch                                      3/8
  Verifying  : postgresql-9.2.24-1.el7_5.x86_64                             4/8
  Verifying  : opennms-webapp-jetty-23.0.4-1.noarch                         5/8
  Verifying  : postgresql-server-9.2.24-1.el7_5.x86_64                      6/8
  Verifying  : postgresql-libs-9.2.24-1.el7_5.x86_64                        7/8
  Verifying  : opennms-core-23.0.4-1.noarch                                 8/8

Installed:
  opennms.noarch 0:23.0.4-1

Dependency Installed:
  jicmp.x86_64 0:2.0.3-1.el7.centos
  jicmp6.x86_64 0:2.0.2-1.el7.centos
  opennms-core.noarch 0:23.0.4-1
  opennms-webapp-jetty.noarch 0:23.0.4-1
  postgresql.x86_64 0:9.2.24-1.el7_5
  postgresql-libs.x86_64 0:9.2.24-1.el7_5
  postgresql-server.x86_64 0:9.2.24-1.el7_5

Complete!
OK
PostgreSQL initialize                 ... OK
PostgreSQL set auth from ident to md5 ... OK
Start PostgreSQL database             ... OK
PostgreSQL systemd enable             ... OK

Enter database username: opennms
Enter database password:

Generate OpenNMS data source config   ... OK
Initialize OpenNMS                    ... FAILED
[ksoren@engrappt2801 opennms-install-1.3]$   Verifying  : jicmp6-2.0.2-1.el7.centos.x86_64                             1/8
Start PostgreSQL database             ... OK
PostgreSQL systemd enable             ... OK

Enter database username: opennms
Enter database password:

Generate OpenNMS data source config   ... OK
Initialize OpenNMS                    ... FAILED

This is the second time I have tried this on a fresh VM.

**Comment by indigo423** [comment]
Can you please share the content of the `bootstrap.log` file which is created with the error message? You can use a link to https://gist.github.com if the output is too large.

**Comment by indigo423** [comment]
If you have a setup with GUI installed you probably run into this problem:

https://opennms.discourse.group/t/installing-opennms-fails-with-classnotfoundexception-com-sun-tools-attach-attachnotsupportedexception/52?u=indigo

The GUI install on a server comes with a Java Runtime Environment. OpenNMS requires a Development Kit.

**Comment by keylowgee** [comment]
@indigo423 Where would the bootstrap.log file be?

**Comment by keylowgee** [comment]
[bootstrap.log](https://github.com/opennms-forge/opennms-install/files/3048804/bootstrap.log)

**Comment by keylowgee** [comment]
[ksoren@engrappt2801 bin]$ ${OPENNMS_HOME}/bin/runjava -c
/bin/java
[ksoren@engrappt2801 bin]$ javac -version
bash: javac: command not found...
Similar command is: 'java'

**Comment by keylowgee** [comment]
[ksoren@engrappt2801 opt]$ sudo yum list installed | grep java
[sudo] password for ksoren:
java-1.7.0-openjdk.x86_64         1:1.7.0.181-2.6.14.8.el7_5
java-1.7.0-openjdk-headless.x86_64
java-1.8.0-openjdk.x86_64         1:1.8.0.171-8.b10.el7_5
java-1.8.0-openjdk-headless.x86_64
javamail.noarch                   1.4.6-8.el7         @rhel-x86_64-workstation-7
javapackages-tools.noarch         3.4.1-11.el7        @anaconda/7.4
python-javapackages.noarch        3.4.1-11.el7        @anaconda/7.4
tzdata-java.noarch                2018e-3.el7         @rhel-x86_64-workstation-7

**Comment by indigo423** [comment]
You don't have the correct OpenJDK installed. You have to install `java-1.8.0-openjdk-devel` and make it your default JVM with `update-alternatives --config java`. Run `runjava -s` in /opt/opennms/bin` afterward which will set the default JDK for OpenNMS. You can verify the Java version OpenNMS is using in `/opt/opennms/etc/java.conf`.

**Comment by indigo423** [comment]
I know, OpenJDK is probably the most stupid name they could pick for the project cause there is a Java Runtime Environment (JRE) and a Java Development Kit (JDK). The package `java-1.8.0-openjdk` is just the JRE and `java-1.8.0-openjdk-devel` is the JDK.

**Comment by keylowgee** [comment]
I just ran the command: yum install  java-1.8.0-openjdk-devel.x86_64

I wanted to to check that java and javac. were working.
[root@engrappt2801 ~]# update-alternatives --config javac

There is 1 program that provides 'javac'.

  Selection    Command
-----------------------------------------------
*+ 1           java-1.8.0-openjdk.x86_64 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-2.el7_6.x86_64/bin/javac)


[root@engrappt2801 ~]# [root@engrappt2801 ~]# update-alternatives --config java
  Selection    Command
-----------------------------------------------
*+ 1           java-1.8.0-openjdk.x86_64 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-2.el7_6.x86_64/jre/bin/java)
   2           java-1.7.0-openjdk.x86_64 (/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.181-2.6.14.8.el7_5.x86_64/jre/bin/java)

Than I did an install of opennms and it failed. 
I notice that neither of those references the **java-1.8.0-openjdk-devel** and I do not know how to make it if the yum install does not work. Why is the configuration of java dependencies not done as part of the easy installer?

**Comment by indigo423** [comment]
It is not easy to handle a Java environment accordingly. For example, you install a Server with a GUI it comes with a JRE. To deal with this issues the easy installer would need to give you possibilities to manage your Java environment and I would like not go down this rabbit hole. Instead we have modified the installer for Horizon 25 to check if an OpenJDK 11 Development Kit is installed and if not through it back to the user and ensure OpenJDK 11 Development Kit is installed properly as a dependency.
