### ISSUE TITLE
failed to get D-bus connection: Operation not permitted

### ISSUE THREAD

**Issue by mjooris** [opennms-forge/opennms-install#20]
hi,

running clean centos 7.6.1810 out of docker on my synology nas. 

script ends with: PostgreSQL initialize  ...failed please check the bootstrap.log.

in the bootstrap.log file i can find:

CentOS Linux release 7.6.1810 (Core)                                                                                          
CentOS Linux release 7.6.1810 (Core)                                                                                          
/usr/bin/sudo                                                                                                                 
CentOS Linux release 7.6.1810 (Core)                                                                                          
/usr/bin/sudo                                                                                                                 
java-11-openjdk-devel.x86_64              1:11.0.3.7-0.el7_6            @updates                                              
warning: /var/tmp/rpm-tmp.VN0Ira: Header V3 DSA/SHA1 Signature, key ID 5b9efd43: NOKEY                                        
runjava: Looking for an appropriate JVM...                                                                                    
runjava: Checking for an appropriate JVM in JAVA_HOME...                                                                      
runjava: Skipping... JAVA_HOME not set.                                                                                       
runjava: Checking JVM in the PATH: "/etc/alternatives/java"...                                                                
runjava: Did not find an appropriate JVM in the PATH: "/etc/alternatives/java"                                                
runjava: Searching for a good JVM...                                                                                          
runjava: Found a good JVM in "/usr/lib/jvm/java-11-openjdk-11.0.3.7-0.el7_6.x86_64/bin/java".                                 
runjava: Value of "/usr/lib/jvm/java-11-openjdk-11.0.3.7-0.el7_6.x86_64/bin/java" stored in configuration file.               
**Failed to get D-Bus connection: Operation not permitted                                                                       
failed to find PGDATA setting in postgresql.service**                                                                           
CentOS Linux release 7.6.1810 (Core)                                                                                          
/usr/bin/sudo                                                                                                                 
java-11-openjdk-devel.x86_64        1:11.0.3.7-0.el7_6           @updates                                                     
runjava: Looking for an appropriate JVM...                                                                                    
runjava: Checking for an appropriate JVM in JAVA_HOME...                                                                      
runjava: Skipping... JAVA_HOME not set.                                                                                       
runjava: Checking JVM in the PATH: "/etc/alternatives/java"...                                                                
runjava: Did not find an appropriate JVM in the PATH: "/etc/alternatives/java"                                                
runjava: Searching for a good JVM...                                                                                          
runjava: Found a good JVM in "/usr/lib/jvm/java-11-openjdk-11.0.3.7-0.el7_6.x86_64/bin/java".                                 
runjava: Value of "/usr/lib/jvm/java-11-openjdk-11.0.3.7-0.el7_6.x86_64/bin/java" stored in configuration file.               
Failed to get D-Bus connection: Operation not permitted                                                                       
failed to find PGDATA setting in postgresql.service                                                                           
CentOS Linux release 7.6.1810 (Core)                                                                                          
/usr/bin/sudo                                                                                                                 
java-11-openjdk-devel.x86_64        1:11.0.3.7-0.el7_6           @updates                                                     
runjava: Looking for an appropriate JVM...                                                                                    
runjava: Checking for an appropriate JVM in JAVA_HOME...                                                                      
runjava: Skipping... JAVA_HOME not set.                                                                                       
runjava: Checking JVM in the PATH: "/etc/alternatives/java"...                                                                
runjava: Did not find an appropriate JVM in the PATH: "/etc/alternatives/java"                                                
runjava: Searching for a good JVM...                                                                                          
runjava: Found a good JVM in "/usr/lib/jvm/java-11-openjdk-11.0.3.7-0.el7_6.x86_64/bin/java".                                 
runjava: Value of "/usr/lib/jvm/java-11-openjdk-11.0.3.7-0.el7_6.x86_64/bin/java" stored in configuration file.               
Failed to get D-Bus connection: Operation not permitted                                                                       
failed to find PGDATA setting in postgresql.service                                                                           
"bootstrap.log" 43L, 2475C 

hope you can help me,
thanks in advance!

regards,

**Comment by indigo423** [comment]
You can't use the installer scripts in a Docker environment. A Docker container image doesn't have systemd. If you want to build your own Docker Image files, you can have a look in our [opennms-container](https://github.com/OpenNMS/opennms/tree/develop/opennms-container) directory in our source tree where we build OCI files.
