### ISSUE TITLE
✨ Prevent unplanned updates of OpenNMS Horizon

### ISSUE THREAD

**Issue by indigo423** [opennms-forge/opennms-install#29]
As a user, you want to install automatic system and security updates for the operating system. OpenNMS Horizon requires manual steps when the system upgrades. To avoid unplanned maintenance windows dealing with upgrades we should disable automatic updates with `apt hold` and `dnf config-manager --disable opennms-repo-stable-*`.

**Comment by SuperDaveAU** [comment]
@indigo423 - It's a bit late, but I've just submitted a pull request for this install script to disable the repo to ensure we dont update. 
https://github.com/opennms-forge/opennms-install/pull/41

**Comment by SuperDaveAU** [comment]
Just tested this on Ubuntu 22.04.01 LTS and I now must go through the screens to setup postfix. 
I do that, and then I get this screen after that, which is a bit confusing as it indicates that I need to do something extra...

![opennms-manualinstall](https://github.com/user-attachments/assets/f50ddc92-44e8-4e29-81de-1deeaaeb96fd)

I then hit enter thoguh and the installer continues.
OpenNMS then successfully installs.
