### ISSUE TITLE
file not found in ubuntu 18.04

### ISSUE THREAD

**Issue by ansftnmz** [opennms-forge/opennms-install#33]
i used command "wget https://github.com/opennms-forge/opennms-install/archive/master.zip" to download the installer but the file is not found in ubuntu 18.04. 

<img width="398" alt="TinyTake09-01-2024-01-10-58" src="https://github.com/opennms-forge/opennms-install/assets/149318636/2ef75d3c-a759-4dcc-817a-b6a8b76aa710">

**Comment by indigo423** [comment]
Can you explain where you got the link from? It seems like you found a place where we need to fix the link to a correct version of it. Thank you.

**Comment by indigo423** [comment]
@ansftnmz can you try to use `wget https://raw.githubusercontent.com/opennms-forge/opennms-install/main/bootstrap-debian.sh`? It seems like you have followed an outdated link to an old master.zip file which doesn't exist anymore. If you have issues or you can tell us the place where you found that link, we are happy to fix it if we can. Please don't hesitate to reopen the issue if you want.
