### ISSUE TITLE
Problem with installation while authenticating with sudo

### ISSUE THREAD

**Issue by neroxyr** [opennms-forge/opennms-install#34]
Just installing a new instance of opennms on AlmaLinux, but after the "Authenticate with sudo" it prompts me the password for th user. After I hit entered this error shows:

**bootstrap-yum.sh: Error on line 136: sudo echo -n "" 2>> "${ERROR_LOG}"**

**Comment by indigo423** [comment]
I tried to replicate the problem with an Alma Linux 9.3 but couldn't replicate it. Is it possible your user isn't allowed to use sudo? Can you share the content of your bootstrap.log?

**Comment by indigo423** [comment]
@neroxyr If you run into a similar problem or you can share some logs from the bootstrap.log, please don't hesitate to reopen this issue.
