### ISSUE TITLE
🪲Debian script: default database name should be 'opennms' but is empty

### ISSUE THREAD

**Issue by md1986** [opennms-forge/opennms-install#35]
When executing the script, I encountered a bug when just continuing with the defaults. The database cannot be created because the default database name is not 'opennms' as is written but instead empty. The error occurs in the Debian script.

**Comment by indigo423** [comment]
I think in general, the script doesn't have a good default fallback handling when using read. I think we need to do something like this:

```bash
read -p "Database name for OpenNMS Horizon [opennms]: " DB_NAME
name=${DB_NAME:-opennms}
```

**Comment by AAm-kun** [comment]
Wasted 2 hours debugging this bugs. Maybe should have checked earlier.

**Comment by indigo423** [comment]
@md1986 I've created a separate issue #38 to address this problem, which is off-topic for this issue here. Thank you for bringing this up.
