### ISSUE TITLE
bootstrap-debian.sh on Ubuntu 14.04

### ISSUE THREAD

**Issue by yvesguerinmtl** [opennms-forge/opennms-install#8]
Dear,

Please do not relay on /etc/issue to discover the Os version use
`uname -a | grep $REQUIRED_SYSTEMS`
because I changed my /etc/issue and it does not contain anymore the word **Ubuntu**

Regards

**Comment by indigo423** [comment]
I would like to change the script to use the `lsb_release -a` command instead. Would it work for you as well? What do you think?

Here is a sample output in Debian and should work on Ubuntu as well.

`
root@stretch:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
`

Thank you for reporting and help to improve our scripts.

**Comment by indigo423** [comment]
Ah ok, sorry with `$REQUIRED_SYSTEMS` you mean the variable inside the script. I got it, make the change to make the script more reliable.
