### ISSUE TITLE
Problems installing OpenNMS on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by yvesguerinmtl** [opennms-forge/opennms-install#9]
Dear,

You forget to install/check Oracle Java JDK-8 but you said the contrary on your welcome screen (showDisclaimer())  that you will do it !

` bash bootstrap-debian.sh -r stable -m debian.opennms.eu

This script installs OpenNMS on  your system. It will
install  all  components necessary  to  run  OpenNMS.

The following components will be installed:

 - Oracle Java 8 JDK
 - PostgreSQL Server
 - OpenNMS Repositories
 - OpenNMS with core services and Webapplication
 - Initialize and bootstrapping the database
 - Start OpenNMS
`

Regards,

Yves

**Comment by indigo423** [comment]
The Oracle JDK will be installed as a dependency when OpenNMS Horizon gets installed. You will be asked during the setup to accept the Oracle License agreement.

In case the user has already installed an OpenJDK the Oracle setup is probably skipped cause you have a Java dependency installed.

Do you run with OpenJDK? You can easily check in "Admin -> Help/Support -> About the OpenNMS Web Console"

**Comment by mathieudup382** [comment]
Hi,

When I tried to install NMS I always have and error at the end : 
Setting up opennms-server (22.0.0-1) ...

 *** Installation complete.  You must still run the installer at
 *** $OPENNMS_HOME/bin/install to be sure your database is up
 *** to date before you start OpenNMS.  See the install guide at
 *** http://www.opennms.org/wiki/Installation:Debian and the
 *** release notes for details.

Setting up opennms-webapp-jetty (22.0.0-1) ...
Setting up opennms-source (22.0.0-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for ureadahead (0.100.0-20) ...
Processing triggers for systemd (237-3ubuntu10) ...
Processing triggers for rsyslog (8.32.0-1ubuntu4) ...
Processing triggers for ufw (0.35-5) ...
Errors were encountered while processing:
 iplike-pgsql10
 opennms-db
 opennms
E: Sub-process /usr/bin/dpkg returned an error code (1)
OK


Generate OpenNMS data source config   ... OK
Initialize OpenNMS                    ... OK
PostgreSQL revoke super user role     ... OK
PostgreSQL revoke create db role      ... OK
Starting OpenNMS                      ... OK
OpenNMS systemd enable                ... OK

Congratulations
---------------

OpenNMS is up and running. You can access the web application with

http://this-systems-ip:8980

Login with username admin and password admin

Please change immediately the password for your admin user!
Select in the main navigation "Admin" and go to "Change Password"

Thank you computing with us.


Im on Ubunto 18.04 LTS on a VM 

thanks

**Comment by indigo423** [comment]
@mathieudup382 can you please share the output from the `bootstrap.log` file to see if there are more details reported on your error?

**Comment by indigo423** [comment]
I tried to reproduce your problem and it seems like this is related to our IP like package which has trouble to deal with PostgreSQL 10.3. We had already a bug report in our tracker which is https://issues.opennms.org/browse/NMS-9925. We will track down this issue and thank you for reporting.

**Comment by indigo423** [comment]
Verified on Ubuntu 18.04 LTS with PostgreSQL 10 version and is solved in https://issues.opennms.org/browse/NMS-9925.
